apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dynamicsecrets-deployment
  labels:
    app: dynamicsecrets
spec:
  selector:
    matchLabels:
      app: dynamicsecrets
  template:
    metadata:
      labels:
        app: dynamicsecrets
    spec:
      hostNetwork: yes
      containers:
      - name: dynamicsecrets
        image: joeburke30/dynamicsecrettest:1.0
        imagePullPolicy: Never
        ports:
        - name: svc-port
          containerPort: 8890
          hostPort: 8890
