apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubesecret-deployment
  labels:
    app: kubesecret
spec:
  selector:
    matchLabels:
      app: kubesecret
  template:
    metadata:
      labels:
        app: kubesecret
    spec:
      hostNetwork: yes
      containers:
      - name: kubesecret 
        image: joeburke30/localkubesecrettest:1.0
        imagePullPolicy: Never
        env:
        - name: SECRETS_DEMO_USER
          valueFrom:
            secretKeyRef:
              name: spring-security
              key: spring.user.name
        - name: SECRETS_DEMO_USER_PASSWD
          valueFrom:
            secretKeyRef:
              name: spring-security
              key: spring.user.password
        ports:
        - name: svc-port
          containerPort: 8889
          hostPort: 8889
