apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: localconfig-deployment
  labels:
    app: localconfig
spec:
  selector:
    matchLabels:
      app: localconfig
  template:
    metadata:
      labels:
        app: localconfig
    spec:
      hostNetwork: yes
      containers:
      - name: localconfig
        image: joeburke30/localconfigtest:1.0
        imagePullPolicy: Never
        ports:
        - name: svc-port
          containerPort: 8888
          hostPort: 8888
